zimaboard_nfs_media_directory: "/var/nfs/media"
zimaboard_nfs_shared_ip_range: "192.168.1.0/24"

config_dir: "/home/{{ ansible_user }}"

docker_network_name: "main_network"

ha_version: "2025.10.1"
ha_port: 8123

pihole_version: "2025.11.0"
pihole_port: 8080
pihole_hostname: "zimaboard"
pihole_timezone: "Europe/Berlin"
pihole_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  64343435656531343666633836353931363733313336336233613961366564636438373063633539
  6665366235303266366462333734616334303734646130390a643833306265643666643864393738
  62363334623739346432613865363166333737323635646137636162366166663065386333356336
  6131363234343537330a646261323936393139356330653739646366353461383462343663666334
  3538

nginx_version: "1.29.1"

smartctl_exporter_version: "v0.14.0"
smartctl_exporter_port: "9633"
