zimaboard_nfs_media_directory: "/var/nfs/media"
zimaboard_nfs_shared_ip_range: "192.168.1.0/24"

config_dir: "/home/{{ ansible_user }}"

docker_network_name: "main_network"

ha_version: "2026.1.3"
ha_port: 8123

music_assistant_version: "2.6.3"

pihole_version: "2025.11.0"
pihole_port: 8080
pihole_hostname: "zimaboard"
pihole_timezone: "Europe/Berlin"
pihole_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  64343435656531343666633836353931363733313336336233613961366564636438373063633539
  6665366235303266366462333734616334303734646130390a643833306265643666643864393738
  62363334623739346432613865363166333737323635646137636162366166663065386333356336
  6131363234343537330a646261323936393139356330653739646366353461383462343663666334
  3538

smartctl_exporter_version: "v0.14.0"
smartctl_exporter_port: "9633"

nextcloud_url: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  35393532613839646638373530386330393636333563616636616232333136346333333930343430
  6430636463373164616533393238393165346566306462320a656132643666313234393166353666
  32343531393665663764386166346236666362353061623961383638613864623766663337656238
  3630356666626535320a653530333731313961626632333632626632386464383235316162326561
  66303363383733656130633932346366333737666131396438613635646266333632383363663264
  35376133356636303366336536383031663434326366346232306234353266343834386362646134
  613931653731376361316665333734623938
nextcloud_user: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  63306266656134313635373432666638383361333530393162613032623062633634613333396262
  6332616661656131633565653764343037646534393564340a616666313963633263396434343663
  33323030626134613334306339386332616435363132386438383830323664313839376436353139
  3736323161313034370a636363313763383530343133366534633539656265323865393061316263
  6430
nextcloud_pass_obscured: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  35656433383636663038316239306565373037646535643435656634343761353330323863616336
  3534643736613930666362663833666533623835393562620a666530373133663265616236313134
  39613434646336623864386163313831613337373530393932363731633463393533663836376630
  3164383662326164310a356166633964323266623432353534386330316330393632323139376262
  33376662656234613433626465666264653834373433383737393834636239613863396335316439
  3464643935353837363737396635613461373364346238333162

local_nfs_path: "/var/nfs/media/completed/music"
remote_target: "nextcloud:music/torrent"
