---
k3s_version: v1.35.0+k3s1
ansible_user: home-lab
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: ""
extra_agent_args: ""

tailscale_auth_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  66313432613762396566663737663964346564333931613362343730353131373862646331633437
  6365363737323038656335396165643932386338393235630a343430613637336434636231616530
  63626565306533323736626462636637623633373033313364663836333735646130653832366134
  3330313039353862300a616637336165613631353535623330613561653365663038646132613332
  39653535393739363631363336653865316237313062656431656562636662613035336438396232
  33663161663964393630343630376666616661303263363939336265616137396333333364313361
  306331326464323537303130363861663466
