---
k3s_version: v1.34.1+k3s1
ansible_user: home-lab
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: ""
extra_agent_args: ""

tailscale_auth_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  63633766643633316533666139666163666161613538333364356364323131333866313736613761
  6463356163633438356630396533643636623762303939650a313463653239303739346337306664
  61633635666461653634393033396435303661616637653431633163353235373366653434376430
  6366363230396233340a373031323939313961633138396134313666633733306565663837613639
  66366430313936636233363661303732663561353665626262613835613862303961336365643337
  34646539643639376637666365663561393962303365393839643831613832306262396437373835
  333137616162366230623439323639323763
