---
- include_tasks: prereq.yml
- include_tasks: nfs.yml
- include_tasks: network.yml
- include_tasks: pi-hole.yml
- include_tasks: home-assistant.yml
- include_tasks: cron.yml
- include_tasks:
    file: rclone.yml
    apply:
      tags:
        - rclone
  tags:
    - rclone
