velero_version: v1.13.0
velero_gcp_sa_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  32326665393534303565643835623233653033373565383339346137313035613433323639663134
  3565323664613231386463353462303663366261306537630a643664333938623430363464343532
  32333061653830643332636464316538306138303736313665663035393765393938316364636164
  3535353463303431330a356531343138396533386565363730353039636565653663333337353637
  32396230333739303863363532346235663562643836666164346662336132356332393366643538
  62616537366162343735613462346266623665633062396638653837643864653065383835313362
  65336336616361323261613238363437353438646463383638623134393533636137643433333130
  63633336653030636436613335656232326136666339666332626636666166323765303138643938
  32306661373361646565396634643835653337356161613135383332373633616133386134366137
  36393865373865363231633434303535633466353731656364316535636231386332343035353230
  66613439653033623231363337653430303862363735656134663630343032663863646664353636
  65303637366134663066393833633830333630656564386434323831306231653361326462303066
  62653262323061616337383665653832636632393063623438633062323963313335366435346565
  66386266643965373765653438306637373436663039333262373831363332386634376538383332
  66326132383630666634653335666561363537613161323333616636303839653132613535646431
  66663365393639396339626635623261646532303439383362666234323933636534383838303239
  39373766373038306437386666306131336231616631306538613465306464313133303539666437
  62623832326465346234336536333663373561396632383661376130653863616665396362313533
  35633566633337363666316339643364306436653266383836393534643834353764376532313833
  64326565343632313436306535656130383832336234376634306430306664613233363036386136
  31333633313439656462623762303633376336323233643566636465353731626661636362383336
  38386436346365326263396438646231663462333831666435633263653333626534386636376137
  38353138333263363538653862646439346632643030366462313838356233383737323066313765
  37376464343336353866306661633962373232363966303032303638316437356338363530356231
  63356333656466386536653833323362386433653938663165303563663062393164373365353738
  31343635663231343964636434336339623662366237626439333161656635363535366635313239
  66356162333733393061353762346439323638336265396464623065313232363334333131376363
  36653362383033656334383065333866616637313663643930353131336630373234663331376661
  38363630366431363366396233663562303437313763383730623438666237626564616637373032
  66306439373965633630313664626139653332633065626539363365333237326565643839336138
  35353863666161353664323664613333363233616163393663313236386336633962343330643836
  66376131383631613739363963646663666231376433383363366539363530303763383439376433
  65623162353933656639303462386338643362663665663161616230313666613162306363666433
  61363265363832666666653437333032656639363837363166306363646566353337613865653761
  37613366663065383062396638613238306237633537393638346630306365643731343461383164
  30383938646339663333633966633336663630373137666261353666386339373463326538626436
  33656363343531313934663061616136363764303731333966633930623830323632663661396236
  62323632636131343632313037656533323261633562643236636133346561373561373030393637
  61303363386662376364626635653739316536343432323862616562643436313465373365663735
  36303465383830646265623162656336626233656162353866636663303839343065393664626133
  63663561613736373038353931313535666639323334303462633934636439653936336231643266
  30633031383030366334383362386532633233353261656331353731333535353735343132376339
  34653866646534346630663163356465613662333239333236623166633733323064656132383738
  32613239666266656137383232653765623039343134653136623735336533613333323331353937
  36366130666439313866653662636430333033353134633639653531386162316366633235646135
  37323233343663393234366630353338626234353863613436303535303133313464633565623430
  38313535366464623833336631666339333363656439396231636562386365363864643937343064
  31343061303431323463643534333035353338343837383634393039333432333863383530313163
  36353961303966656665346238623463353238373564343564323263363435616665663033373764
  36666364323261656436623362653563323766363962366637356534313662316436343966313535
  61663664336163366531306164346161636237363465313737346463363334623031343965306633
  36343237313234653730616636353663333137656236636137653035353761303665313630653931
  62656661613638373833626264356339383163323262336136303535353834356161393464336165
  31323234313561653931396638346236326139386264323131393531333634383234333264366631
  63353637393334303931626236623931626261646431663062343037313161356437613762333462
  32373431323635343730623762343465633734373033656465613030333234613136336137373539
  63333831636662383933666136306235663630653939663562393732623337663964356138353030
  63356362626664643639333465376338313634653365323030363635306161326464366664323038
  36633338316564306438386561313966363630346164666537363734663433303031636137303530
  65653736383338653062373637343431336137643166313139393364636534386332356161333430
  35323338353334326165323335623133613332656132376630376334343938386438633036336263
  39643632333534303631616662616664363030653039373533313562373034393333326432333136
  32663234626436363130636539386439663833396365613538623632363134356661633931366532
  37653665393831616237323063613335363032303535363230343362303138353037363232356237
  36613163316330353864393232346639326634303934343933353366633730363437653961623733
  31613265643535323737393632636239343339626437316564303533363539353966303266336632
  65343539316461613933313065633034343465396638363737333936316264646465646134663831
  64633864663637373961346636326331373161386532623031653462303235616531303866623664
  39323861326363306166633839346464383133613661373136393639386430633565663436346466
  36623262626536343262313532643066353762333663316536623933366166623865353732623434
  36613035653538633262323333306538646537633766306562666365366666396161396461626564
  31643130353233366439613732323562666339306238323336333638633237346433313338333265
  63353431656462653932663038353162636565656639393832366534623639636337323233343836
  64396162356666366365653761343032343965663037383236303731303239343431373337376135
  33316532643566666333363239653066323561356262636239313934626537366437313830656336
  64363863333265663538643530663133333034353932623261353838653938663031633933633537
  37333034333362663632396630356664643130396535323234653666396435313266656536656434
  32363731363832353433343364316466663933363831643534323437306134373339376463623363
  62373635393064663962653532613833653738636331666336336339653735633266616330643335
  31363237323630383338323036313165333537353737326632643230386566383864336530396362
  39323036393761626161616631636661663136333337626334663538343362383738353064343162
  33323439356535393136323033333730623136336334613738626161653034303565663931636338
  64656135613432376536326162313163643434383366373363663631656433653731353066303737
  64376437383861333532643335313438643838313233393131636466663764303033613761323130
  36633262646434323966643739663161346630663666363335663465306235343332363131663661
  38383339343366356239343035633130653166663661333138313665643130373866313936666136
  37633136343430343465356366653264663831306639353162373237653939323039316632353466
  37386233393162303835326465333564326364353766346564373561316163366534316566653130
  34353330343333376137623665373534346438313837373762393832343339303532663263636266
  38326562373037333731306437636233333065323839333138303935666431373964303033333339
  38623064373730363733366565396261623361383536393231383233373338623163303936326434
  37616664646333376533636436316435623963653635303666316361623633653863356466636639
  39653761373838363338376631646163623366653665393036366234306164636562313739653664
  63396439356134363437663664633336646465373236326634333233656237346264353835396139
  33366565336533656331653662303134616262323035386638306532373063623337613034383065
  31353036303364396230373531353062346139323938373863623165373131646233396537316334
  61633862653338303833353063626538663936393031646430633931346661613163306637366163
  39626135623531633662303834336438646363626330346338353464343262386264353139313062
  31303436316366633439396461666261336634623438636430353065303964373335656331363766
  33623435356137623962316264363639633431653661373432666239373433646335353439316632
  63336239353830376661656333633665323838626163633531393038333966306262633638333364
  38373836306362633361323230363739633133653663333039386265366130616133366262323264
  61343663363264386166396362323839336262313763366138383662373930313230633462666134
  31326437303463386533393462383035396630333964613132336666306662366263316230643430
  65376236396338666462343561633563393836666639333938393535646163386432626263306163
  30393335626434616231643837616234353333373136383464353333636333656431373964373864
  38396137373462326534616134363362333431616466373334663431656161336163363866653262
  64373930346538666132663134396538396165353564393063333837633237626132386235366637
  64353932306639663836616361326364326139303261323437623165643463636530323363383864
  38656135623034636261343535323838666666653462636234323462633833643834356139376462
  62666432646631616539303865323366396134396533626632613639616339616430346461653239
  34383732303235373035653138626630393863363638356435353431653365636630376330316138
  35623536326664356437383235376265383863646264656235326531626438653033326165306466
  33393265326566313436396230616538363737383038326464626532303939653462356264323036
  66656637396430343763356531386234356539306132646338653431613231333664333464663962
  63393537353332633333373165633537373064313835313563343462653333323036383365353134
  63383033376335643764623438366265323935616263623736646631643462353435353034643838
  31376163616332336364363164363038373235313030303138316463633831656465373530333939
  39643033383030616633366365383636353466393861303864336332363065613461613131303466
  39393566343130396538383564623661383637653933333962333565653236343131356439353430
  30333662383637623764666533636433396335353962336263363265333061356664
velero_gcp_sa_key_temporary_location: /tmp/velero-gcp-sa-key.json
velero_gcp_bucket: home-lab-velero-backups

internal_ca_cert: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  34663561336130633536393437623131323339656631653666353862306538643065653835646466
  3331323064386638613266303233316631326631623738310a353263616431623231353139616464
  36336361613931666365373035623939323833313333343665626233636232656632623365336233
  3661303864356130300a636137633065393539613034393562643635383435386332313533343634
  61363737313730336264626339323461366562396635323163306464643939636332303666376362
  39333738666461626639633632346434343061646230636130333037386634346433336134306535
  31363133643761333135633663393366393162356139653262373064636333343064393565613064
  61666631333463363637646630376162313335323730353436383233613135663931303435626330
  37663763616139303966333137626436636239366261656533643163656130366363663738666231
  38396539373036363162316262636131306162653763656362373563633561303335373733323563
  33663037646634306262633064343135383536643165336233313039393935656563313233393132
  66333234616363393866376262346466316437376436656235663334623934376336376231643762
  61633061636235313236636331316362303930343931643064653330316234316133613430393561
  35633033613635393938323836666630343933393335666130666530616632323633663131666635
  63376330326166626339343937343764376236613735386164633734653637623265616162313236
  34303964653932333961643761373830316563626332666337303538633638336366393636386232
  61636531366536356363613931386537633433363133353337396234326633383836396437363833
  61386532616166313232376338376161313738636536633666393561303833373164653066383738
  31313363646162363331343931346663356363393532373032663462663766313538316336366265
  38633164386237383162366365333366363037656433656231653437373338663066396632396539
  31623437636631373763636238376439306361613131376634333532336130633932326130343630
  35323538323036636530663363313962636336353562343531666134313033346262303631303463
  35643239313164383766623365343037613934363232346238333936643965373363363836316338
  39626165366261363436626166393162343939353564326332346338303337313361636134663939
  31643664613165353431366231346637363663313931373837616334653430303562303036666638
  38623765356338656261386339383337346561663961336637616337636164336164386535643832
  32366264356631313130633463376365663930383432373662343430663538643366383939363237
  34636133303862316266303063336134376432396531653639646163373265346565343561373132
  62326534316432376364633735653234343637353439356335323062303438333531313032323932
  65396232396231373963346636383166613034383732626239343934363234376637383339326666
  65656139656264313764353064376234636439363537313238353438313263346539393533383636
  39626437636130333138313735373866303037383839323961623831623865386635663337303734
  38313861386338616535333265313339396336653265653739356331663235326230363462373566
  30383564663933353936653066306631623965623139653763383665356637373534643133356466
  64373831613038663166653538326531623635623539376336653932613630386565653032303037
  65653363643338333736313434666231636466663730633632663262623732386331313761636131
  39343335653235333066366633373163313566363533623761336531633831356136366365313635
  61303362623533316533373534373738643366366365353366623562663439653662386466643933
  66626563643162313132656134306666383831313536303366313363633035343334623564666565
  38666665636132613734346563376136313361363632313831306562616437386638356562363237
  66613634623661616262636431346561346638353465623633316530353730613038373464386262
  33663339646333303932346366376365316266613166303633666464623263643235373562306437
  66663431356461376561656665383535323166323763666362656430666338393937613164346230
  39613135613033333636393933373733643366643739323831356330313232643363386564303832
  30666331353163636631316366323363633030316436613831323434383930356366326164343231
  32316130396566316135373065303435373030306263316339343731663561643839386562373561
  63306662663233393663323830613631623032306431626130396435356531343130306462626237
  64623338613063646236616139303363303137353934356662323831646364353030663635656564
  62306136373139326335313737313033636339366465393763366535373137383936383532366565
  39626639616439656562666530353565643735323138326433353030613166626238316662376430
  62633962653866633438336235643331633234626431353336646430386235363338633361306630
  33623936356239363164613562326465643435653962343232373336393537363838306463336262
  65313664386130343031373361376139643961623864383034353339353030666263643864343066
  35356136633539376132656531306235336264313631653833646633336465663933353638663463
  35383832313836373065326634376636366437346363323733313737636235383337326430646439
  65653663646332366437383464386661353533316630643466663734653630316562343534633465
  65396530383066346464363162333537373831353966336565326335663962623630353661326436
  63366463323965383733393061626364666439306562306162356236613038316664383463616563
  37363162333731373836653934356236363339306337316562646238353432326462373665643264
  37303831616234616165623430386664623237313565303963373538653361383263336536323562
  66393330653061323630613837613266346561643035663062343663316634653039616532616535
  32393761666466393130346665623630663031613965336335636233363034363533323534623938
  65623338333365646262303331393633343161336333636534333237373636323161373934386638
  66316236363737623137326335316637363138623362623633383937666532396634363239633839
  33363134623265383133316636666261323536626464643530393533306437303835666430366630
  61393862346136316232313133313338353836333865653631643365333966396339346536626663
  623536633537386538383063383731633932
internal_ca_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  30383138396236333132313333333437316563646539323436383765623963623036363134643633
  3633643135313135383337386238333064643335616262640a363235313736636231663635363663
  65643764663639303433383732363163333363343336623738306663653038376230313536353938
  3430633163303866370a363937336536353532643833633735316462316233663061343531336134
  31366466616534386264643765306132643233656164383464383864643632323264373833633263
  37646532353162303763353131663861353864313361303432616162393965323861356531346634
  35333261666434363730653433373334383138356632663133373539663930326463323962633137
  65303164393062636437643336653366376662666539613837336531643562333139663161613638
  31336562656666396332376566653162346462393531663766646265633233656565636233316363
  65396563343162303438663163633263623364333664636164376434323231386234633731393137
  61376639623937356433303532326634356339396331633962376161646566373135323839646338
  38363862373062376635373531613537363561383839623964653538613737656334613762363236
  62643263653533393066636132643739643039303265663137376335363664393133353230613530
  66653434306536373737636236313435323339313839653464333966643439373938343662386532
  36333638323765616135613163653632353432386637646138613530653066316264336535356563
  37323662666362306566313736343738373737353866666266666537613430366239323234613562
  30653239633637333565303038336162633730643532393439383436663536646330633665393730
  35633862343738346230326430373430623937623332626332386665396430633966613466343339
  30313763353562653263356532333662636163633266353731396237363736386261316631663966
  63326364393935363564333430626631656539646335313138343233626334626263393833353931
  33326337313432326237316566386461326539653066616463363333333333653732373430353137
  30353133636135373337363164316463626430383139366162353039316230333565343234323732
  61393430386339393739306661643161356162393830633861623036336635353431316263646366
  38623730323333313833376536333731366639396136306266636430633831393333393966383963
  6136
